In [26]:
%pip install pandas
%pip install numpy

Requirement already satisfied: pandas in g:\Github Projects\chronic-kidney-disease-prediction\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in g:\Github Projects\chronic-kidney-disease-prediction\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in g:\Github Projects\chronic-kidney-disease-prediction\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in g:\Github Projects\chronic-kidney-disease-prediction\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in g:\Github Projects\chronic-kidney-disease-prediction\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in g:\Github Projects\chronic-kidney-disease-prediction\.venv\Lib\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

In [27]:
import pandas as pd
import numpy as np

In [28]:
df_data = pd.read_csv('../data/kidney_disease.csv')

In [29]:
print(df_data)

      id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent
..   ...   ...   ...    ...  ...  ...     ...       ...         ...
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no

    classification
0              ckd
1              ckd
2              ckd
3              ckd
4              ckd
..             ...
395         notckd
396         notckd
397         notckd
398         notckd
399         notckd

[400 rows x 26 columns]

In [30]:
df_data.info()
df_data.shape

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    str
 7   pc              335 non-null    str
 8   pcc             396 non-null    str
 9   ba              396 non-null    str
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    str
 17  wc              295 non-null    str
 18  rc              270 non-null    str
 19  htn             398 non-null    str
 20  dm              398 non-null    str
 21  cad             398 non-null    str
 22  appet           399 non-null    str
 23  pe              399 non-null    str
 24  ane             399 non-null    str
 25  classification  400 non-null    str
dtypes: float64(11), int64(1), str(14)
memory usage: 81.4 KB

(400, 26)

In [31]:
df_data.drop('id', axis=1, inplace=True)

In [32]:
df_data.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [33]:
df_data.describe()

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
count,391.000000,388.000000,353.000000,354.000000,351.000000,356.000000,381.000000,383.000000,313.000000,312.000000,348.000000
mean,51.483376,76.469072,1.017408,1.016949,0.450142,148.036517,57.425722,3.072454,137.528754,4.627244,12.526437
std,17.169714,13.683637,0.005717,1.352679,1.099191,79.281714,50.503006,5.741126,10.408752,3.193904,2.912587
min,2.000000,50.000000,1.005000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,3.100000
25%,42.000000,70.000000,1.010000,0.000000,0.000000,99.000000,27.000000,0.900000,135.000000,3.800000,10.300000
50%,55.000000,80.000000,1.020000,0.000000,0.000000,121.000000,42.000000,1.300000,138.000000,4.400000,12.650000
75%,64.500000,80.000000,1.020000,2.000000,0.000000,163.000000,66.000000,2.800000,142.000000,4.900000,15.000000
max,90.000000,180.000000,1.025000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,17.800000

In [34]:
df_data.columns=['age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar', 'red_blood_cells', 'pus_cell', 'pus_cell_clumps', 'bateria', 'blood_glucose_random', 'blood_urea', 'serum_creatinine', 'sodium', 'potassium', 'haemoglobin', 'packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count', 'hypertension', 'diabetes_mellitus', 'coronary_artery_disease', 'appetite', 'pedal_edema', 'anemia','class']

In [35]:
df_data.head()

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bateria,blood_glucose_random,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [36]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      391 non-null    float64
 1   blood_pressure           388 non-null    float64
 2   specific_gravity         353 non-null    float64
 3   albumin                  354 non-null    float64
 4   sugar                    351 non-null    float64
 5   red_blood_cells          248 non-null    str
 6   pus_cell                 335 non-null    str
 7   pus_cell_clumps          396 non-null    str
 8   bateria                  396 non-null    str
 9   blood_glucose_random     356 non-null    float64
 10  blood_urea               381 non-null    float64
 11  serum_creatinine         383 non-null    float64
 12  sodium                   313 non-null    float64
 13  potassium                312 non-null    float64
 14  haemoglobin              348 non-null    float64
 15  packed_cell_volume       330 non-null    str
 16  white_blood_cell_count   295 non-null    str
 17  red_blood_cell_count     270 non-null    str
 18  hypertension             398 non-null    str
 19  diabetes_mellitus        398 non-null    str
 20  coronary_artery_disease  398 non-null    str
 21  appetite                 399 non-null    str
 22  pedal_edema              399 non-null    str
 23  anemia                   399 non-null    str
 24  class                    400 non-null    str
dtypes: float64(11), str(14)
memory usage: 78.3 KB

In [37]:
text_columns=['packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count']
for i in text_columns:
    print(df_data[i].dtype)

str
str
str

In [38]:
def convert_to_numeric(columns):
    for i in columns:
        df_data[i] = pd.to_numeric(df_data[i], errors='coerce')

In [39]:
convert_to_numeric(text_columns)

In [40]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      391 non-null    float64
 1   blood_pressure           388 non-null    float64
 2   specific_gravity         353 non-null    float64
 3   albumin                  354 non-null    float64
 4   sugar                    351 non-null    float64
 5   red_blood_cells          248 non-null    str
 6   pus_cell                 335 non-null    str
 7   pus_cell_clumps          396 non-null    str
 8   bateria                  396 non-null    str
 9   blood_glucose_random     356 non-null    float64
 10  blood_urea               381 non-null    float64
 11  serum_creatinine         383 non-null    float64
 12  sodium                   313 non-null    float64
 13  potassium                312 non-null    float64
 14  haemoglobin              348 non-null    float64
 15  packed_cell_volume       329 non-null    float64
 16  white_blood_cell_count   294 non-null    float64
 17  red_blood_cell_count     269 non-null    float64
 18  hypertension             398 non-null    str
 19  diabetes_mellitus        398 non-null    str
 20  coronary_artery_disease  398 non-null    str
 21  appetite                 399 non-null    str
 22  pedal_edema              399 non-null    str
 23  anemia                   399 non-null    str
 24  class                    400 non-null    str
dtypes: float64(14), str(11)
memory usage: 78.3 KB

In [41]:
text_columns=['packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count']
for i in text_columns:
    print(df_data[i].dtype)

float64
float64
float64

In [42]:
missing = df_data.isnull().sum()
missing

age                          9
blood_pressure              12
specific_gravity            47
albumin                     46
sugar                       49
red_blood_cells            152
pus_cell                    65
pus_cell_clumps              4
bateria                      4
blood_glucose_random        44
blood_urea                  19
serum_creatinine            17
sodium                      87
potassium                   88
haemoglobin                 52
packed_cell_volume          71
white_blood_cell_count     106
red_blood_cell_count       131
hypertension                 2
diabetes_mellitus            2
coronary_artery_disease      2
appetite                     1
pedal_edema                  1
anemia                       1
class                        0
dtype: int64

In [43]:
def mean_value_imputation(df_data, column):
    mean_values = df_data[column].mean()
    df_data[column]=df_data[column].fillna(mean_values)
def mode_value_imputation(df_data, column):
    mode_values = df_data[column].mode()[0]
    df_data[column]=df_data[column].fillna(mode_values)

In [44]:
num_cols=[col for col in df_data.columns if df_data[col].dtype in ['float64']]
cat_cols=[col for col in df_data.columns if df_data[col].dtype == 'str']

In [45]:
for col_name in num_cols:
    mean_value_imputation(df_data, col_name)
for col_name in cat_cols:
    mode_value_imputation(df_data, col_name)

In [46]:
missing = df_data.isnull().sum()
missing[missing > 0]

Series([], dtype: int64)

In [47]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      400 non-null    float64
 1   blood_pressure           400 non-null    float64
 2   specific_gravity         400 non-null    float64
 3   albumin                  400 non-null    float64
 4   sugar                    400 non-null    float64
 5   red_blood_cells          400 non-null    str
 6   pus_cell                 400 non-null    str
 7   pus_cell_clumps          400 non-null    str
 8   bateria                  400 non-null    str
 9   blood_glucose_random     400 non-null    float64
 10  blood_urea               400 non-null    float64
 11  serum_creatinine         400 non-null    float64
 12  sodium                   400 non-null    float64
 13  potassium                400 non-null    float64
 14  haemoglobin              400 non-null    float64
 15  packed_cell_volume       400 non-null    float64
 16  white_blood_cell_count   400 non-null    float64
 17  red_blood_cell_count     400 non-null    float64
 18  hypertension             400 non-null    str
 19  diabetes_mellitus        400 non-null    str
 20  coronary_artery_disease  400 non-null    str
 21  appetite                 400 non-null    str
 22  pedal_edema              400 non-null    str
 23  anemia                   400 non-null    str
 24  class                    400 non-null    str
dtypes: float64(14), str(11)
memory usage: 78.3 KB

In [48]:
print(f"diabetes_mellitus:- {df_data['diabetes_mellitus'].unique()}")
print(f"coronary_artery_disease:- {df_data['coronary_artery_disease'].unique()}")
print(f"class:- {df_data['class'].unique()}")

diabetes_mellitus:- <StringArray>
['yes', 'no', ' yes', '\tno', '\tyes']
Length: 5, dtype: str
coronary_artery_disease:- <StringArray>
['no', 'yes', '\tno']
Length: 3, dtype: str
class:- <StringArray>
['ckd', 'ckd\t', 'notckd']
Length: 3, dtype: str

In [49]:
df_data['diabetes_mellitus'] = df_data['diabetes_mellitus'].replace(to_replace={' yes':'yes', '\tyes':'yes','\tno':'no'})
df_data['coronary_artery_disease'] = df_data['coronary_artery_disease'].replace(to_replace='\tno', value='no')
df_data['class'] = df_data['class'].replace(to_replace='ckd\t', value='ckd')

In [50]:
print(f"diabetes_mellitus:- {df_data['diabetes_mellitus'].unique()}")
print(f"coronary_artery_disease:- {df_data['coronary_artery_disease'].unique()}")
print(f"class:- {df_data['class'].unique()}")

diabetes_mellitus:- <StringArray>
['yes', 'no']
Length: 2, dtype: str
coronary_artery_disease:- <StringArray>
['no', 'yes']
Length: 2, dtype: str
class:- <StringArray>
['ckd', 'notckd']
Length: 2, dtype: str